from enum import Enum


class AuditEvent(str, Enum):
    USER_LOGIN = "USER_LOGIN"
    USER_LOGIN_FAILED = "USER_LOGIN_FAILED"
    USER_LOGOUT = "USER_LOGOUT"
    USER_CREATED = "USER_CREATED"
    USER_ROLE_CHANGED = "USER_ROLE_CHANGED"
    USER_DEACTIVATED = "USER_DEACTIVATED"
    USER_ACTIVATED = "USER_ACTIVATED"
    USER_PASSWORD_CHANGED = "USER_PASSWORD_CHANGED"
    USER_ACCOUNT_LOCKED = "USER_ACCOUNT_LOCKED"
    TOKEN_REVOKED = "TOKEN_REVOKED"

    HAR_UPLOADED = "HAR_UPLOADED"
    ANALYSIS_STARTED = "ANALYSIS_STARTED"
    ANALYSIS_COMPLETED = "ANALYSIS_COMPLETED"

    OPENAPI_GENERATED = "OPENAPI_GENERATED"

    RAG_INDEX_STARTED = "RAG_INDEX_STARTED"
    RAG_INDEX_COMPLETED = "RAG_INDEX_COMPLETED"
    RAG_SEARCH_EXECUTED = "RAG_SEARCH_EXECUTED"

    PLAN_GENERATED = "PLAN_GENERATED"

    DRY_RUN_STARTED = "DRY_RUN_STARTED"
    DRY_RUN_COMPLETED = "DRY_RUN_COMPLETED"

    BULK_FILE_UPLOADED = "BULK_FILE_UPLOADED"
    MAPPING_SUGGESTED = "MAPPING_SUGGESTED"
    BULK_VALIDATED = "BULK_VALIDATED"
    BULK_DRY_RUN_STARTED = "BULK_DRY_RUN_STARTED"
    BULK_EXECUTION_STARTED = "BULK_EXECUTION_STARTED"
    BULK_EXECUTION_COMPLETED = "BULK_EXECUTION_COMPLETED"

    EXECUTION_APPROVED = "EXECUTION_APPROVED"
    EXECUTION_REJECTED = "EXECUTION_REJECTED"
    EXECUTION_STARTED = "EXECUTION_STARTED"
    EXECUTION_COMPLETED = "EXECUTION_COMPLETED"
    EXECUTION_FAILED = "EXECUTION_FAILED"

    AUTOMATION_PLAN_GENERATED = "AUTOMATION_PLAN_GENERATED"
    AUTOMATION_EXECUTED = "AUTOMATION_EXECUTED"

    REPORT_VIEWED = "REPORT_VIEWED"
    SETTINGS_UPDATED = "SETTINGS_UPDATED"

    UPLOAD_CLEANUP_RUN = "UPLOAD_CLEANUP_RUN"
