from typing import List

from app.models.endpoint import Endpoint


def _convert_schema(schema: dict | None) -> dict:
    return schema or {}


def _build_parameters(endpoint: Endpoint) -> List[dict]:
    parameters = []
    for part in endpoint.path.split("/"):
        if part.startswith("{") and part.endswith("}"):
            name = part[1:-1]
            parameters.append({
                "name": name,
                "in": "path",
                "required": True,
                "schema": {"type": "string"},
            })
    return parameters


def build_openapi_document(
    title: str,
    version: str,
    endpoints: List[Endpoint],
) -> dict:
    document = {
        "openapi": "3.0.3",
        "info": {
            "title": title,
            "version": version,
            "description": "Generated by ARIA from HAR traffic analysis.",
        },
        "paths": {},
    }

    for endpoint in endpoints:
        path = endpoint.path
        method = endpoint.method.lower()

        if path not in document["paths"]:
            document["paths"][path] = {}

        schema = endpoint.schema

        canonical_key_safe = (
            endpoint.canonical_key
            .replace(" ", "_")
            .replace("/", "_")
            .replace("{", "")
            .replace("}", "")
        )

        operation = {
            "summary": endpoint.business_action or endpoint.canonical_key,
            "description": (
                f"Auto-generated endpoint from traffic analysis. "
                f"Business domain: {endpoint.business_domain or 'unknown'}."
            ),
            "operationId": endpoint.business_action or canonical_key_safe,
            "tags": [endpoint.business_domain or "default"],
            "parameters": _build_parameters(endpoint),
            "responses": {},
        }

        if schema and schema.request_schema:
            operation["requestBody"] = {
                "required": True,
                "content": {
                    "application/json": {
                        "schema": _convert_schema(schema.request_schema)
                    }
                },
            }

        if schema and schema.status_codes:
            for status_code in schema.status_codes:
                operation["responses"][str(status_code)] = {
                    "description": "Auto-inferred response",
                    "content": {
                        "application/json": {
                            "schema": _convert_schema(schema.response_schema)
                        }
                    },
                }
        else:
            operation["responses"]["200"] = {"description": "Successful response"}

        if schema and schema.auth_required:
            document.setdefault("components", {})
            document["components"].setdefault("securitySchemes", {})

            if schema.auth_type == "bearer_token":
                document["components"]["securitySchemes"]["BearerAuth"] = {
                    "type": "http",
                    "scheme": "bearer",
                    "bearerFormat": "JWT",
                }
                operation["security"] = [{"BearerAuth": []}]
            elif schema.auth_type == "api_key":
                document["components"]["securitySchemes"]["ApiKeyAuth"] = {
                    "type": "apiKey",
                    "in": "header",
                    "name": schema.auth_header_name or "x-api-key",
                }
                operation["security"] = [{"ApiKeyAuth": []}]

        document["paths"][path][method] = operation

    return document
