from enum import Enum


class EventName(str, Enum):
    HAR_UPLOADED = "HAR_UPLOADED"
    HAR_PARSED = "HAR_PARSED"
    TRAFFIC_CLEANED = "TRAFFIC_CLEANED"
    ENDPOINTS_NORMALIZED = "ENDPOINTS_NORMALIZED"
    SCHEMAS_INFERRED = "SCHEMAS_INFERRED"
    WORKFLOW_DISCOVERED = "WORKFLOW_DISCOVERED"
    REGISTRY_SAVED = "REGISTRY_SAVED"
    OPENAPI_GENERATED = "OPENAPI_GENERATED"
    RAG_INDEXED = "RAG_INDEXED"
    RAG_SEARCHED = "RAG_SEARCHED"
    PLAN_GENERATED = "PLAN_GENERATED"
    PLAN_VALIDATED = "PLAN_VALIDATED"
    EXECUTION_STARTED = "EXECUTION_STARTED"
    EXECUTION_COMPLETED = "EXECUTION_COMPLETED"
    EXECUTION_FAILED = "EXECUTION_FAILED"
    REPORT_GENERATED = "REPORT_GENERATED"
